apiVersion : apps/v1
kind: Deployment
metadata:
  name: maksimfraloupipelinesjavascriptdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maksimfraloupipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: maksimfraloupipelinesjavascriptdocker 
    spec:
      containers:
        - name: maksimfraloupipelinesjavascriptdocker 
          image: maxfacr001.azurecr.io/maksimfraloupipelinesjavascriptdocker
          ports:
          - containerPort: 8080